# Generated by Django 5.2.8 on 2025-11-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10, verbose_name='Номер талона')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('called', 'Вызван'), ('serving', 'Обслуживается'), ('done', 'Обслужен'), ('skipped', 'Пропущен')], default='waiting', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('called_by_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operatorwindow', verbose_name='Вызван окном')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Талон очереди',
                'verbose_name_plural': 'Талоны очереди',
            },
        ),
    ]
