# Generated by Django 5.2.8 on 2025-11-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_queueticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции (вес, адрес и т.д.)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость услуги')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время завершения')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.queueticket', verbose_name='Талон')),
            ],
            options={
                'verbose_name': 'Операция обслуживания',
                'verbose_name_plural': 'Операции обслуживания',
            },
        ),
    ]
